### ISSUE TITLE
barre de navigation 

### ISSUE THREAD

**Issue by jmj69** [ComicScrip/lyon-react-mars22-p2g4#10]
# Le besoin

En tant que utilisateur , je souhaite créer une barre de navigation , afin de faciliter l'accès aux différentes pages 

## Critères et considérations spécifiques

- [ ] Conformité aux écrans "accueil / choix parcours / détails parcours / vue live / récap du parcours / historique parcours / contact us about us" sur la maquette
- [ ] fluidité de navigation entre les pages 

### Scénarios de test

- pas à pas (debuger)
- contrôle des liens entre les pages 

### Actions à réaliser

- se rendre sur la page "header.js" accessible depuis l'URL `./components/header.js` 
- créer le menu "burger" pour la partie responsive
- un menu déroulant apparait quand on clique sur le "burger"
- intégration de la partie "météo"
- intégration du logo "pic'n'move"

### Vérifications

- [ ] On accède bien à la partie météo quand on clique sur le logo "nuage"
- [ ] Le menu se déroule quand on clique sur le burger 
- [ ] Dans le menu déroulant cliquer sur les noms de page nous renvoi bien vers ces pages 
- [ ] On revient sur la page d'accueil quand on clique sur le logo 

### A faire

- [ ] 
- [ ] 

### (A ne pas faire)

- Ceci sort du scope : ...
- ...

**Comment by Isma69** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/WCS---Projet-2-624eabc1ba43900018ca3cf0/issues/ComicScrip/lyon-react-mars22-p2g4/10?planning-poker) with ZenHub @fflachat @jmj69 @Sim-guy
