### ISSUE TITLE
Formulaire de contact

### ISSUE THREAD

**Issue by ChrichriR** [ComicScrip/lyon-react-mars22-p2g4#12]
# Le besoin

En tant qu'utilisateur, je souhaite contacter l'équipe développement , afin de soumettre une nouvelle idée ou encore de signaler un bug.

## Critères et considérations spécifiques

- [ ] Conformité à l'écran par rapport aux maquettes mobile et desktop
- [ ] Message de validation d'envoi ou d'erreur lié au champs concerné

#### Actions à réaliser

- se rendre sur la page contact depuis la page './contact'
- remplir le champ email et message avec les bonnes informations
- cliquer sur le bouton pour envoi
- appuyer sur Enter pour envoi

#### Verifications

- [ ] On entre les bonnes informations
- [ ] Le message de bon envoi apparait

#### Actions à réaliser

- se rendre sur la page contact depuis la page './contact'
- remplir le champ email et message avec les mauvaises informations (email vide et/ou invalide et/ou message vide)
- cliquer sur le bouton pour envoi
-  appuyer sur Enter pour envoi

#### Verifications

- [ ] On entre les mauvaises informations
- [ ] Le message d'erreur apparait 

## A faire

- [ ] Faire un composant ContactPage
- [ ] Faire la structure du formulaire
- [ ] Faire le style du formulaire
- [ ] Programmer l'envoi du formulaire
- [ ] Ajouter la validation des champs
- [ ] Ajouter les messages succès et erreur. (utiliser react Toastify = https://www.npmjs.com/package/react-toastify)

## (A ne pas faire)

- Envoyer un mail

**Comment by Isma69** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/WCS---Projet-2-624eabc1ba43900018ca3cf0/issues/ComicScrip/lyon-react-mars22-p2g4/12?planning-poker) with ZenHub @fflachat @jmj69 @Sim-guy
