### ISSUE TITLE
accès réseaux sociaux

### ISSUE THREAD

**Issue by fflachat** [ComicScrip/lyon-react-mars22-p2g4#18]
# Le besoin

En tant qu'utilisateur, je souhaite accéder aux réseaux sociaux du projet , afin de partager et suivre ce super projet. 

## Critères et considérations spécifiques

- [ ] Conformité aux écrans de la maquette et remarques clients 

#### Actions à réaliser

- se rendre sur les pages twitter, facebook et instagram accessible depuis les URL en cliquant sur les boutons icônes correspondants  

#### Verifications

- [ ] On voit bien apparaitre une page facebook à l'écran

## A faire

- [x] bien disposer les logos au bon endroit 
- [ ] lier les logos vers la page facebook 

## (A ne pas faire)

- mélanger les logos 
- déformer et ne pas respecter les proportions des logos

**Comment by ComicScrip** [comment]
C'est un peu chelou de faire pointer tous les liens vers facebook, non ? 
Creer une page pour les différents liens, sinon ça ne sert pas à grand chose

**Comment by jmj69** [comment]
bonjour,
merci pour la remarque
pas de soucis je peux orienter les liens vers des pages différentes
merci et bonne journée
JMJ
