### ISSUE TITLE
Possibilité de relancer un parcours depuis le journal / récap

### ISSUE THREAD

**Issue by fflachat** [ComicScrip/lyon-react-mars22-p2g4#24]
# Le besoin

En tant qu'utilisateur, je souhaite consulter mon historique afin de refaire un parcours déjà terminé.

## Critères et considérations spécifiques

- [ ] Conformité aux maquettes
- [ ] Les parcours que l'utilisateur a déjà fait sont sauver dans le journal

#### Actions à réaliser

- se rendre sur la page "journal" accessible depuis l'URL `/journal`.
- cliquer sur une des vignettes parcours
- cliquer sur le bouton start pour recommencer le parcours

#### Verifications

- [ ] Le parcours se relance bien

## A faire

- [ ] Sauvegarder un parcours dans le local storage
- [ ] Faire une page détaillée des parcours dans journal 
- [ ] Ajouter un bouton pour relancer un parcours qui renvoie vers la vue live

**Comment by ComicScrip** [comment]
Pour moi, il faut uniquement sauvegarder les infos dans le localstorage, on ne peut pas encore faire d'authentification avec  l'API donc exit les routes qui renvoient des résultats personnalisés en fonction de l'utilisateur

**Comment by fflachat** [comment]
> Pour moi, il faut uniquement sauvegarder les infos dans le localstorage, on ne peut pas encore faire d'authentification avec l'API donc exit les routes qui renvoient des résultats personnalisés en fonction de l'utilisateur

J'ai supprimé la partie BDD / API !
