### ISSUE TITLE
confirmation d'envoi/réception de mail + lien GitHub

### ISSUE THREAD

**Issue by ChrichriR** [ComicScrip/lyon-react-mars22-p2g4#49]
# Le besoin

En tant que qu'utilisateur, je souhaite envoyer un mail pour contacter les dev et que quand je clique sur un portrait ça m'emmène sur un lien github , afin de connaitre un peu mieux les développeurs et communiquer avec eux.

## Critères et considérations spécifiques

- [ ] Conformité avec la maquette

#### Actions à réaliser

- se rendre sur la page "contact" accessible depuis l'URL `/contact`
- remplir les champs correctement
- cliquer le bouton envoyer
- aller sur la boite mail liée à l'adresse mail renseignée

#### Vérifications

- [ ] On reçoit bien un mail de confirmation d'envoi à l'adresse mail que l'on a renseignée

#### Actions à réaliser

- se rendre sur la page "contact" accessible depuis l'URL `/contact`
- cliquer sur une des images
- une nouvelle page s'ouvre sur la page github du nom associé

#### Verifications

- [ ] Quand on clique sur une image on a bien une nouvelle page qui s'ouvre sur une page github liée au nom

## A faire

- [ ] Créer une boite mail au nom de l'appli
- [ ] Coder l'envoi du mail vers le mail de l'appli
- [ ] Coder l'envoi de confirmation d'envoi à faire suivre vers l'adresse mail renseignée dans le champ mail de l'appli
- [ ] Créer le lien entre une page github et l'image correspondante sur l'appli

**Comment by ComicScrip** [comment]
issue modifiée et validée
