### ISSUE TITLE
Vue live

### ISSUE THREAD

**Issue by ChrichriR** [ComicScrip/lyon-react-mars22-p2g4#51]
# Le besoin

En tant qu'utilisateur , je souhaite avoir le calcul de la distance qu'il me reste à parcourir, la perte de calorie, et ma vitesse de croisière afin d'évaluer mon effort

## Critères et considérations spécifiques

- [ ] Conformité à la maquette

#### Actions à réaliser

- Se rendre sur la page "parcours" accessible depuis l'URL `/paths`
- Choisir un parcours
- Démarrer le parcours

#### Verifications

- [x] On voit un bouton de lancement du chrono 
- [x] Quand on lance le chrono, le bouton laisse place à deux autres boutons, pause et stop
- [x] Quand on clique sur pause, il se transforme en start et inversement.
- [x] la carte constamment est re-centrée sur la position de l'utilisateur

## A faire

- [x] Design des boutons
- [x] Modifier le curseur apparaissant sur la map (point au lieu d'une flèche)
- [x] Faire des fonctions de calculs pour la vitesse, la conso de calories et la distance qu'il reste à parcourir.
- [x] Faire en sorte que la carte reste centrée sur le point.

## (A ne pas faire)

- le calcul de la distance restante, des calories consommées et de la vitesse de croisière seront affichés en dur

**Comment by ComicScrip** [comment]
Validé
