### ISSUE TITLE
Filtrage des parcours

### ISSUE THREAD

**Issue by Sim-guy** [ComicScrip/lyon-react-mars22-p2g4#57]
# Le besoin

En tant qu'utilisateur , je souhaite pouvoir filtrer les parcours afin d'accéder plus rapidement à celui voulu.

## Critères et considérations spécifiques

- [ ] Filtre possible des parcours par distance, localisation, difficulté

#### Actions à réaliser

- Accéder aux choix de  parcours depuis la page parcours (/paths) ou l'historique (/journal)
- Cocher la case correspondante à mon choix

#### Verifications

- [x] Les filtres par distance, localisation, difficulté est actif
- [x]  En cas d'absence de résultat, un message apparait

## A faire

- [x] Modifier le filtre existant
- [x] Filtrer les parcours grâce à différents input

**Comment by ComicScrip** [comment]
validé
