### ISSUE TITLE
Intégration de la météo

### ISSUE THREAD

**Issue by fflachat** [ComicScrip/lyon-react-mars22-p2g4#7]
# Le besoin

En tant qu'utilisateur, je souhaite pouvoir connaitre la météo du jour afin de mieux préparer ma sortie. 

## Critères et considérations spécifiques

- [x] -Après avoir réussi à avoir mis en place des requêtes pour récupérer les données que nous voulons sur l'API.

- [x] - Il faut avoir les données sur la météo du jour avec la température et l'icône correspondant.

- [x] -Il faut avoir les prévisions météorologiques sur une semaine de disponible et les icônes qui correspondent  

#### Verifications

- [ ]
- [ ]
- [ ] 

## A faire

- [x] Lire la documentation de l'API météo : Openweathermap
- [x] Se renseigner sur les données que fournie l'API 
- [x] Faire une requête initiale à l'API en fonction de la localisation dès le démarrage de l'application
- [x] Faire une requête pour récupérer l'icone du temps ou relier chaque catégorie de temps à une icone 

## (A ne pas faire)

- Ceci sort du scope : ...
- ...

- [ ]

**Comment by Isma69** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/WCS---Projet-2-624eabc1ba43900018ca3cf0/issues/ComicScrip/lyon-react-mars22-p2g4/7?planning-poker) with ZenHub @fflachat @jmj69 @Sim-guy
